MODEL:
  META_ARCHITECTURE: "GeneralizedRCNN"
  WEIGHT: "catalog://ImageNetPretrained/MSRA/R-101"
  DOMAIN_ADAPTATION_ON: True
  BACKBONE:
    CONV_BODY: "R-101-FPN"
    OUT_CHANNELS: 256
  RPN:
    USE_FPN: True
    ANCHOR_STRIDE: (4, 8, 16, 32, 64)
    ASPECT_RATIOS: (0.8, 1.0, 1.2)
    PRE_NMS_TOP_N_TRAIN: 1000
    PRE_NMS_TOP_N_TEST: 1000
    POST_NMS_TOP_N_TEST: 300
    POST_NMS_TOP_N_TRAIN: 300
    FPN_POST_NMS_TOP_N_TEST: 300
    FG_IOU_THRESHOLD: 0.6
    NMS_THRESH: 0.7
  ROI_HEADS:
    USE_FPN: True
    NMS: 0.1
  ROI_BOX_HEAD:
    NUM_CLASSES: 2
    POOLER_RESOLUTION: 7
    POOLER_SCALES: (0.25, 0.125, 0.0625, 0.03125)
    POOLER_SAMPLING_RATIO: 2
    FEATURE_EXTRACTOR: "FPN2MLPFeatureExtractor"
    PREDICTOR: "FPNPredictor"
  DA_HEADS:
    DA_IMG_GRL_WEIGHT: 0.1
DATASETS:
  TRAIN: ("gfda_cocostyle",)
  SOURCE_TRAIN: ("gfda_cocostyle",)
  TARGET_TRAIN: ("etis_psuedo_cocostyle",)
  TEST: ("etis_cocostyle",)
INPUT:
  MIN_SIZE_TRAIN: (384, 400, 426, 468, 500, 512)
  MAX_SIZE_TRAIN: 800
  MIN_SIZE_TEST: 512
  MAX_SIZE_TEST: 800
DATALOADER:
  SIZE_DIVISIBILITY: 32
SOLVER:
  BASE_LR: 0.001
  WEIGHT_DECAY: 0.0001
  STEPS: (30000, 50000)
  MAX_ITER: 60000
  CHECKPOINT_PERIOD: 90000
  IMS_PER_BATCH: 2
TEST:
  IMS_PER_BATCH: 2
OUTPUT_DIR:
  "da_debug"
